- hosts: localhost
  connection: local
  become: true
  tasks:
  - name: Unnstall nginx
    apt:
      name: nginx
      state: absent
      autoremove: yes
      autoclean: yes
      # update_cache: true
    register: nginx_install
    # failed_when: nginx_install.cache_update_time> 1
  # - name: Copy nginx file over
  #   copy:
  #     src: nginx.conf
  #     dest: /etc/nginx/nginx.conf
  #   register: nginx_config
  #   # failed_when:  nginx_config.diff.before.path == nginx_config.diff.after.path
  #   # when: nginx_config.diff.before.path == nginx_config.diff.after.path


  # - name: Restart nginx if needed
  #   service:
  #     name: nginx
  #     state: restarted
  #   when: nginx_config.changed == true
    
  # - name: Debug info from Copy nginx file over
  #   debug:
  #     var: nginx_config
  #     # msg: " {{ nginx_config }} "
